// Copyright (c) 2026 Kirky.X
//! HTTP server implementation

use crate::config::ConfigError;
use crate::core::{ApiMetadata, Registration};
use crate::define_registration;
use axum::body::Body;
use axum::routing::MethodRouter;
use axum::Router;
use uuid::Uuid;

pub mod response;
pub mod security_headers;
pub mod version_routing;

pub use response::{build_fallback_response, build_json_response};
pub use security_headers::SecurityHeaders;
pub use version_routing::{
    build_version_router, version_redirect_middleware, VersionRouterConfig, VersionedRoute,
};

/// Request ID header name
pub(crate) const X_REQUEST_ID: &str = "x-request-id";

/// Generate or extract request ID from request
pub(crate) fn get_or_generate_request_id(req: &axum::http::Request<Body>) -> String {
    req.headers()
        .get(X_REQUEST_ID)
        .and_then(|v| v.to_str().ok())
        .map(|s| s.to_string())
        .unwrap_or_else(|| Uuid::new_v4().to_string())
}

/// HTTP route registration
#[derive(Debug, Clone)]
pub struct HttpRoute {
    /// Route path (may contain module prefix placeholders)
    path: String,
    /// Handler function (includes method routing)
    handler: MethodRouter,
    /// API metadata
    metadata: ApiMetadata,
    /// Module prefix (if any) - used for route grouping
    module_prefix: Option<String>,
}

impl HttpRoute {
    #[allow(missing_docs)]
    pub fn new(
        path: String,
        handler: MethodRouter,
        metadata: ApiMetadata,
        module_prefix: Option<String>,
    ) -> Self {
        Self {
            path,
            handler,
            metadata,
            module_prefix,
        }
    }

    /// Get route path
    pub fn path(&self) -> &str {
        &self.path
    }

    /// Get handler
    pub fn handler(&self) -> &MethodRouter {
        &self.handler
    }

    /// Get metadata
    pub fn metadata(&self) -> &ApiMetadata {
        &self.metadata
    }

    /// Get module prefix
    pub fn module_prefix(&self) -> Option<&str> {
        self.module_prefix.as_deref()
    }
}

// Generated by `define_registration!` macro for unified registration system.
define_registration!(RouteRegistration, HttpRoute, ApiMetadata);

inventory::collect!(HttpRoute);

/// Resolve module prefix for a route path
///
/// This function checks if there's a module prefix available for the given route.
/// In practice, the macro generates inline path resolution, but this provides
/// a runtime fallback for dynamic path construction.
fn resolve_route_path(base_path: &str, module_prefix: Option<&str>) -> String {
    match module_prefix {
        Some(prefix) if !prefix.is_empty() => {
            // Remove leading slash from prefix if present
            let clean_prefix = prefix.trim_start_matches('/');
            format!("/{}/{}", clean_prefix, &base_path[1..])
        }
        _ => base_path.to_string(),
    }
}

fn apply_security_headers(router: Router) -> Router {
    SecurityHeaders::default().apply(router)
}

/// Prevent linker from optimizing away inventory registrations
/// Uses reference iteration to ensure symbols are preserved
#[cfg(feature = "mcp")]
#[inline(never)]
fn preserve_mcp_inventory() {
    // Iterate and count - this forces linker to keep symbols
    let _count = inventory::iter::<crate::mcp::McpToolRegistration>().count();
    let _ = _count; // Suppress unused variable warning
}

/// Prevent linker from optimizing away WebSocket inventory registrations
#[cfg(feature = "websocket")]
#[inline(never)]
fn preserve_websocket_inventory() {
    let _count = inventory::iter::<crate::websocket::WebSocketRoute>().count();
    let _ = _count;
}

/// Prevent linker from optimizing away gRPC inventory registrations
#[cfg(feature = "grpc")]
#[inline(never)]
fn preserve_grpc_inventory() {
    let _count = inventory::iter::<crate::grpc::GrpcRouteRegistration>().count();
    let _ = _count;
}

/// Build HTTP router from registered routes
///
/// This function collects all routes registered via `inventory::submit!`
/// and builds a complete Axum router for serving HTTP requests.
/// Routes are automatically prefixed with their module prefix if available.
///
/// # Returns
/// A basic Axum router with all registered routes
///
/// # Note
/// This is the simplest router building function. For production use,
/// consider using `build_with_config()` for middleware support.
pub fn build() -> Router {
    // Force inventory collection to prevent linker optimization
    // Using inline(never) functions to ensure symbols are preserved
    #[cfg(feature = "mcp")]
    preserve_mcp_inventory();

    #[cfg(feature = "websocket")]
    preserve_websocket_inventory();

    #[cfg(feature = "grpc")]
    preserve_grpc_inventory();

    let mut router = Router::new();

    // First, collect registrations with function pointers
    let registrations: Vec<_> = inventory::iter::<RouteRegistration>().collect();

    // Sort by name and version for deterministic order
    let mut routes: Vec<_> = registrations
        .iter()
        .map(|registration| registration.create())
        .collect();

    // Also collect direct HttpRoute registrations
    for route in inventory::iter::<HttpRoute>() {
        routes.push(route.clone());
    }

    // Sort routes by path for deterministic order
    routes.sort_by_key(|r| r.path.clone());

    // Build router with routes
    for route in routes {
        let prefix = route.module_prefix.as_deref();
        let full_path = resolve_route_path(&route.path, prefix);
        router = router.route(&full_path, route.handler);
    }

    router
}

/// Build HTTP router with version redirect middleware
///
/// This function builds a router with automatic version redirect support.
/// Requests to `/api/{path}` without a version are redirected to `/api/v1/{path}`.
///
/// # Returns
/// An Axum router with version redirect middleware applied
///
/// # Note
/// Use this when you want automatic version fallback for unversioned API requests.
pub fn build_with_redirect() -> Router {
    let router = build();
    router.layer(axum::middleware::from_fn(version_redirect_middleware))
}

/// Build HTTP router with configuration
///
/// This function builds a router with configuration-driven middleware and settings.
/// Applies CORS, authentication, rate limiting, and logging based on the provided config.
///
/// # Arguments
/// * `config` - The application configuration
///
/// # Returns
/// A configured Axum router with all middleware applied
///
/// # Note
/// This is the recommended function for production use. It applies security headers,
/// CORS, rate limiting, compression, and timeout middleware based on the config.
pub fn build_with_config(config: &crate::config::AppConfig) -> Result<Router, ConfigError> {
    #[cfg(feature = "security")]
    use std::sync::Arc;

    const DEFAULT_BODY_LIMIT: usize = 10 * 1024 * 1024;

    let mut router = build();

    // Apply request ID middleware (first to ensure all requests have an ID)
    router = router.layer(axum::middleware::from_fn(
        |mut req: axum::http::Request<Body>, next: axum::middleware::Next| async move {
            let request_id = get_or_generate_request_id(&req);
            req.headers_mut().insert(
                axum::http::header::HeaderName::from_static(X_REQUEST_ID),
                axum::http::HeaderValue::from_str(&request_id).unwrap(),
            );
            let mut response = next.run(req).await;
            response.headers_mut().insert(
                axum::http::header::HeaderName::from_static(X_REQUEST_ID),
                axum::http::HeaderValue::from_str(&request_id).unwrap(),
            );
            response
        },
    ));

    // Apply global body limit
    router = router.layer(tower_http::limit::RequestBodyLimitLayer::new(
        DEFAULT_BODY_LIMIT,
    ));

    // Apply response compression
    router = router.layer(tower_http::compression::CompressionLayer::new());

    // Use configurable request timeout from server config
    let timeout_secs = config.server.request_timeout_secs;
    router = router.layer(tower_http::timeout::TimeoutLayer::with_status_code(
        axum::http::StatusCode::REQUEST_TIMEOUT,
        std::time::Duration::from_secs(timeout_secs),
    ));

    // Apply CORS
    if let Some(cors) = &config.server.cors {
        let cors_layer = crate::config::build_cors_layer(cors)?;
        router = router.layer(cors_layer);
    }

    // Apply security headers
    router = apply_security_headers(router);

    // Apply authentication middleware
    #[cfg(feature = "security")]
    {
        use crate::config::AuthConfig;
        use crate::security::{auth_middleware, AppApiKeyAuth, AuthContext, AuthError, BearerAuth};
        use axum::http::HeaderValue;

        let auth_config = &config.authentication;

        if let AuthConfig::ApiKey {
            header_name,
            prefix,
        } = auth_config
        {
            let auth = Arc::new(AppApiKeyAuth::new());
            let auth_clone = auth.clone();
            let header_name = header_name.clone();
            let prefix = prefix.clone();
            let extract_auth =
                move |req: &axum::http::Request<Body>| -> Result<AuthContext, AuthError> {
                    // Get header value; if missing or malformed, return auth error immediately
                    let header_value = match req
                        .headers()
                        .get(&header_name)
                        .and_then(|v: &HeaderValue| v.to_str().ok())
                    {
                        Some(value) => value,
                        None => return Err(AuthError::MissingAuth),
                    };

                    let client_ip = req
                        .headers()
                        .get("x-forwarded-for")
                        .or_else(|| req.headers().get("x-real-ip"))
                        .and_then(|v: &HeaderValue| v.to_str().ok())
                        .unwrap_or("unknown")
                        .to_string();

                    // Security fix: Validate prefix is not empty before checking
                    // This prevents authentication bypass when prefix is empty
                    if prefix.is_empty() {
                        return Err(AuthError::MissingAuth);
                    }

                    if header_value.starts_with(&prefix) {
                        let key = &header_value[prefix.len()..];
                        if let Some(permissions) = auth.validate_key(key, &client_ip) {
                            Ok(AuthContext {
                                user_id: Some(key.to_string()),
                                permissions,
                                metadata: crate::security::AuthMetadata::default(),
                            })
                        } else {
                            Err(AuthError::MissingAuth)
                        }
                    } else {
                        Err(AuthError::MissingAuth)
                    }
                };
            let middleware = auth_middleware(auth_clone, extract_auth);
            router = router.layer(axum::middleware::from_fn(middleware));
        } else if let AuthConfig::Jwt { secret, .. } = auth_config {
            let auth = Arc::new(BearerAuth::new(secret));
            let auth_clone = auth.clone();
            let extract_auth =
                move |req: &axum::http::Request<Body>| -> Result<AuthContext, AuthError> {
                    // Validate authorization header is present and properly formatted
                    // Empty or malformed headers must be rejected to prevent authentication bypass
                    let header_value = match req
                        .headers()
                        .get("authorization")
                        .and_then(|v: &HeaderValue| v.to_str().ok())
                    {
                        Some(value) => value,
                        None => return Err(AuthError::MissingAuth),
                    };

                    // Validate Bearer token format and non-empty token
                    // Note: "".strip_prefix("Bearer ") returns Some("") - empty token must be rejected
                    let token = match header_value.strip_prefix("Bearer ") {
                        Some(token) if !token.is_empty() => token,
                        _ => return Err(AuthError::InvalidToken),
                    };

                    if let Some(context) = auth.validate_token(token) {
                        Ok(context)
                    } else {
                        Err(AuthError::InvalidToken)
                    }
                };
            let middleware = auth_middleware(auth_clone, extract_auth);
            router = router.layer(axum::middleware::from_fn(middleware));
        }
        // OAuth2 is already checked before this block
        // None is handled by doing nothing
    }

    // Note: 日志初始化已移除，由使用方通过 sdforge::inklog 直接管理
    Ok(router)
}

/// Build HTTP router with hot reload support
///
/// This function builds a router with configuration hot reload support.
/// When the configuration file is modified, the router will automatically
/// reload and apply the new configuration.
///
/// # Arguments
/// * `config_path` - Path to the configuration file (YAML or JSON)
///
/// # Returns
/// A tuple containing:
/// * The configured Axum router
/// * A `ConfigWatcher` that manages configuration updates
///
/// # Example
/// ```no_run
/// use std::path::PathBuf;
///
/// #[tokio::main]
/// async fn main() -> Result<(), Box<dyn std::error::Error>> {
///     let config_path = PathBuf::from("config.toml");
///     let (router, config_watcher) =
///         sdforge::http::build_with_hot_reload(&config_path).await?;
///
///     // Use router and config_watcher as needed
///     let _ = (router, config_watcher);
///     Ok(())
/// }
/// ```
#[cfg(feature = "hot-reload")]
pub async fn build_with_hot_reload(
    config_path: &std::path::Path,
) -> Result<(Router, crate::config::hot_reload::ConfigWatcherImpl), Box<dyn std::error::Error>> {
    use crate::config::hot_reload::ConfigWatcherImpl;
    use std::path::PathBuf;

    let config_path = PathBuf::from(config_path);
    let (config_watcher, _event_receiver) = ConfigWatcherImpl::new(config_path.clone()).await?;

    // Build router with current configuration
    let config = config_watcher.get().await?;
    let router = build_with_config(&config)?;

    Ok((router, config_watcher))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{AppConfig, AuthConfig, CorsConfig, ServerConfig};
    use axum::routing::get;

    /// Test build() returns a valid Router
    #[test]
    fn test_build_returns_router() {
        let router = build();
        // Just verify it doesn't panic
        let _ = router;
    }

    /// Test build_with_redirect() returns Router with middleware
    #[test]
    fn test_build_with_redirect() {
        let router = build_with_redirect();
        // Should have layers applied
        let _ = router;
    }

    /// Test build_with_config with JWT authentication
    #[test]
    fn test_build_with_config_jwt() {
        let config = AppConfig {
            server: ServerConfig {
                host: "0.0.0.0".to_string(),
                port: 3000,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::Jwt {
                secret: "ThisIsAVeryLongSecretKeyWithUppercase123!@#ForTesting".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok(), "Should build successfully with JWT config");
    }

    /// Test build_with_config with ApiKey authentication
    #[test]
    fn test_build_with_config_api_key() {
        let config = AppConfig {
            server: ServerConfig {
                host: "0.0.0.0".to_string(),
                port: 3000,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::ApiKey {
                header_name: "X-API-Key".to_string(),
                prefix: "key-".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(
            result.is_ok(),
            "Should build successfully with ApiKey config"
        );
    }

    /// Test build_with_config with OAuth2 returns error
    #[test]
    fn test_build_with_config_oauth2_error() {
        let config = AppConfig {
            server: ServerConfig {
                host: "0.0.0.0".to_string(),
                port: 3000,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::None,
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok(), "Should succeed with None auth config");
    }

    /// Test build_with_config with CORS configuration
    #[test]
    fn test_build_with_config_cors() {
        let config = AppConfig {
            server: ServerConfig {
                host: "0.0.0.0".to_string(),
                port: 3000,
                request_timeout_secs: 30,
                cors: Some(CorsConfig {
                    allowed_origins: vec!["http://localhost:3000".to_string()],
                    allowed_methods: vec!["GET".to_string(), "POST".to_string()],
                    allowed_headers: vec!["Content-Type".to_string()],
                }),
            },
            authentication: AuthConfig::Jwt {
                secret: "ThisIsAVeryLongSecretKeyWithUppercase123!@#ForTesting".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok(), "Should build successfully with CORS config");
    }

    /// Test HttpRoute structure
    #[test]
    fn test_http_route_creation() {
        use axum::routing::get;

        async fn test_handler() -> &'static str {
            "test"
        }

        let route = HttpRoute::new(
            "/test".to_string(),
            get(test_handler),
            crate::core::ApiMetadata {
                name: "test".to_string(),
                version: "v1".to_string(),
                description: "Test API".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
            None,
        );

        assert_eq!(route.path(), "/test");
        assert_eq!(route.metadata().name(), "test");
        assert!(route.module_prefix().is_none());
    }

    /// Test resolve_route_path function
    #[test]
    fn test_resolve_route_path() {
        // No prefix
        assert_eq!(resolve_route_path("/api/users", None), "/api/users");
        assert_eq!(resolve_route_path("/api/users", Some("")), "/api/users");

        // With prefix
        assert_eq!(
            resolve_route_path("/api/users", Some("v1")),
            "/v1/api/users"
        );
        assert_eq!(
            resolve_route_path("/api/users", Some("/v1")),
            "/v1/api/users"
        );
    }

    /// Test RouteRegistration structure
    #[test]
    fn test_route_registration() {
        async fn test_handler() {}
        let registration = RouteRegistration::new(
            "test",
            "v1",
            || {
                HttpRoute::new(
                    "/test".to_string(),
                    get(test_handler),
                    crate::core::ApiMetadata {
                        name: "test".to_string(),
                        version: "v1".to_string(),
                        description: "".to_string(),
                        cache_ttl: None,
                        is_streaming: false,
                    },
                    None,
                )
            },
            || crate::core::ApiMetadata {
                name: "test".to_string(),
                version: "v1".to_string(),
                description: "".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
        );

        assert_eq!(registration.name, "test");
        assert_eq!(registration.version, "v1");
    }
}
