// Copyright (c) 2026 Kirky.X
//! HTTP server implementation

use crate::config::ConfigError;
use crate::core::{ApiMetadata, Registration};
use crate::define_registration;
use axum::body::Body;
use axum::routing::MethodRouter;
use axum::Router;
use uuid::Uuid;

pub mod response;
pub mod security_headers;
pub mod version_routing;

pub use response::{build_fallback_response, build_json_response};
pub use security_headers::SecurityHeaders;
pub use version_routing::{
    build_version_router, version_redirect_middleware, VersionRouterConfig, VersionedRoute,
};

/// Request ID header name
pub(crate) const X_REQUEST_ID: &str = "x-request-id";

/// Generate or extract request ID from request
pub(crate) fn get_or_generate_request_id(req: &axum::http::Request<Body>) -> String {
    req.headers()
        .get(X_REQUEST_ID)
        .and_then(|v| v.to_str().ok())
        .map(|s| s.to_string())
        .unwrap_or_else(|| Uuid::new_v4().to_string())
}

/// HTTP route registration
#[derive(Debug, Clone)]
pub struct HttpRoute {
    /// Route path (may contain module prefix placeholders)
    path: String,
    /// Handler function (includes method routing)
    handler: MethodRouter,
    /// API metadata
    metadata: ApiMetadata,
    /// Module prefix (if any) - used for route grouping
    module_prefix: Option<String>,
}

impl HttpRoute {
    #[allow(missing_docs)]
    pub fn new(
        path: String,
        handler: MethodRouter,
        metadata: ApiMetadata,
        module_prefix: Option<String>,
    ) -> Self {
        Self {
            path,
            handler,
            metadata,
            module_prefix,
        }
    }

    /// Get route path
    pub fn path(&self) -> &str {
        &self.path
    }

    /// Get handler
    pub fn handler(&self) -> &MethodRouter {
        &self.handler
    }

    /// Get metadata
    pub fn metadata(&self) -> &ApiMetadata {
        &self.metadata
    }

    /// Get module prefix
    pub fn module_prefix(&self) -> Option<&str> {
        self.module_prefix.as_deref()
    }
}

// Generated by `define_registration!` macro for unified registration system.
define_registration!(RouteRegistration, HttpRoute, ApiMetadata);

inventory::collect!(HttpRoute);

/// Resolve module prefix for a route path
///
/// This function checks if there's a module prefix available for the given route.
/// In practice, the macro generates inline path resolution, but this provides
/// a runtime fallback for dynamic path construction.
fn resolve_route_path(base_path: &str, module_prefix: Option<&str>) -> String {
    match module_prefix {
        Some(prefix) if !prefix.is_empty() => {
            // Remove leading slash from prefix if present
            let clean_prefix = prefix.trim_start_matches('/');
            format!("/{}/{}", clean_prefix, &base_path[1..])
        }
        _ => base_path.to_string(),
    }
}

fn apply_security_headers(router: Router) -> Router {
    SecurityHeaders::default().apply(router)
}

/// Prevent linker from optimizing away inventory registrations
/// Uses reference iteration to ensure symbols are preserved
#[cfg(feature = "mcp")]
#[inline(never)]
fn preserve_mcp_inventory() {
    // Iterate and count - this forces linker to keep symbols
    let _count = inventory::iter::<crate::mcp::McpToolRegistration>().count();
    let _ = _count; // Suppress unused variable warning
}

/// Prevent linker from optimizing away WebSocket inventory registrations
#[cfg(feature = "websocket")]
#[inline(never)]
fn preserve_websocket_inventory() {
    let _count = inventory::iter::<crate::websocket::WebSocketRoute>().count();
    let _ = _count;
}

/// Prevent linker from optimizing away gRPC inventory registrations
#[cfg(feature = "grpc")]
#[inline(never)]
fn preserve_grpc_inventory() {
    let _count = inventory::iter::<crate::grpc::GrpcRouteRegistration>().count();
    let _ = _count;
}

/// Build HTTP router from registered routes
///
/// This function collects all routes registered via `inventory::submit!`
/// and builds a complete Axum router for serving HTTP requests.
/// Routes are automatically prefixed with their module prefix if available.
///
/// # Returns
/// A basic Axum router with all registered routes
///
/// # Note
/// This is the simplest router building function. For production use,
/// consider using `build_with_config()` for middleware support.
pub fn build() -> Router {
    // Force inventory collection to prevent linker optimization
    // Using inline(never) functions to ensure symbols are preserved
    #[cfg(feature = "mcp")]
    preserve_mcp_inventory();

    #[cfg(feature = "websocket")]
    preserve_websocket_inventory();

    #[cfg(feature = "grpc")]
    preserve_grpc_inventory();

    let mut router = Router::new();

    // First, collect registrations with function pointers
    let registrations: Vec<_> = inventory::iter::<RouteRegistration>().collect();

    // Map registrations to HttpRoute instances via their create functions
    let mut routes: Vec<_> = registrations
        .iter()
        .map(|registration| registration.create())
        .collect();

    // Also collect direct HttpRoute registrations
    for route in inventory::iter::<HttpRoute>() {
        routes.push(route.clone());
    }

    // Compute the full path (with module prefix) for each route, then
    // deduplicate by full path. Without this, registering the same path
    // via both RouteRegistration and a direct HttpRoute (or twice within
    // either source) would cause Axum to panic with "Cannot register
    // duplicate route" at runtime.
    //
    // Resolution order: later registrations win. Direct HttpRoute entries
    // are appended after RouteRegistration entries, so they take precedence
    // — which matches the expectation that explicit registrations override
    // macro-generated ones.
    let mut seen: std::collections::HashMap<String, HttpRoute> =
        std::collections::HashMap::with_capacity(routes.len());
    for route in routes {
        let prefix = route.module_prefix.as_deref();
        let full_path = resolve_route_path(&route.path, prefix);
        seen.insert(full_path, route);
    }

    // Sort by full path for deterministic router construction order.
    let mut deduped: Vec<_> = seen.into_iter().collect();
    deduped.sort_by(|a, b| a.0.cmp(&b.0));

    for (full_path, route) in deduped {
        router = router.route(&full_path, route.handler);
    }

    router
}

/// Build HTTP router with version redirect middleware
///
/// This function builds a router with automatic version redirect support.
/// Requests to `/api/{path}` without a version are redirected to `/api/v1/{path}`.
///
/// # Returns
/// An Axum router with version redirect middleware applied
///
/// # Note
/// Use this when you want automatic version fallback for unversioned API requests.
pub fn build_with_redirect() -> Router {
    let router = build();
    router.layer(axum::middleware::from_fn(version_redirect_middleware))
}

/// Build HTTP router with configuration
///
/// This function builds a router with configuration-driven middleware and settings.
/// Applies CORS, authentication, rate limiting, and logging based on the provided config.
///
/// # Arguments
/// * `config` - The application configuration
///
/// # Returns
/// A configured Axum router with all middleware applied
///
/// # Note
/// This is the recommended function for production use. It applies security headers,
/// CORS, rate limiting, compression, and timeout middleware based on the config.
pub fn build_with_config(config: &crate::config::AppConfig) -> Result<Router, ConfigError> {
    #[cfg(feature = "security")]
    use std::sync::Arc;

    const DEFAULT_BODY_LIMIT: usize = 10 * 1024 * 1024;

    let mut router = build();

    // Apply request ID middleware (first to ensure all requests have an ID)
    router = router.layer(axum::middleware::from_fn(
        |mut req: axum::http::Request<Body>, next: axum::middleware::Next| async move {
            let request_id = get_or_generate_request_id(&req);
            // Safely insert request ID header — fall back to a static placeholder
            // if the value contains non-ASCII characters (prevents panic on malformed client input)
            let header_value = axum::http::HeaderValue::from_str(&request_id)
                .unwrap_or_else(|_| axum::http::HeaderValue::from_static("invalid-request-id"));
            req.headers_mut().insert(
                axum::http::header::HeaderName::from_static(X_REQUEST_ID),
                header_value.clone(),
            );
            let mut response = next.run(req).await;
            response.headers_mut().insert(
                axum::http::header::HeaderName::from_static(X_REQUEST_ID),
                header_value,
            );
            response
        },
    ));

    // Apply global body limit
    router = router.layer(tower_http::limit::RequestBodyLimitLayer::new(
        DEFAULT_BODY_LIMIT,
    ));

    // Apply response compression
    router = router.layer(tower_http::compression::CompressionLayer::new());

    // Use configurable request timeout from server config
    let timeout_secs = config.server.request_timeout_secs;
    router = router.layer(tower_http::timeout::TimeoutLayer::with_status_code(
        axum::http::StatusCode::REQUEST_TIMEOUT,
        std::time::Duration::from_secs(timeout_secs),
    ));

    // Apply CORS
    if let Some(cors) = &config.server.cors {
        let cors_layer = crate::config::build_cors_layer(cors)?;
        router = router.layer(cors_layer);
    }

    // Apply security headers
    router = apply_security_headers(router);

    // Apply authentication middleware
    #[cfg(feature = "security")]
    {
        use crate::config::AuthConfig;
        use crate::security::{auth_middleware, AppApiKeyAuth, AuthContext, AuthError, BearerAuth};
        use axum::http::HeaderValue;

        let auth_config = &config.authentication;

        if let AuthConfig::ApiKey {
            header_name,
            prefix,
        } = auth_config
        {
            let auth = Arc::new(AppApiKeyAuth::new());
            let auth_clone = auth.clone();
            let header_name = header_name.clone();
            let prefix = prefix.clone();
            let extract_auth =
                move |req: &axum::http::Request<Body>| -> Result<AuthContext, AuthError> {
                    // Get header value; if missing or malformed, return auth error immediately
                    let header_value = match req
                        .headers()
                        .get(&header_name)
                        .and_then(|v: &HeaderValue| v.to_str().ok())
                    {
                        Some(value) => value,
                        None => return Err(AuthError::MissingAuth),
                    };

                    let client_ip = req
                        .headers()
                        .get("x-forwarded-for")
                        .or_else(|| req.headers().get("x-real-ip"))
                        .and_then(|v: &HeaderValue| v.to_str().ok())
                        .unwrap_or("unknown")
                        .to_string();

                    // Security fix: Validate prefix is not empty before checking
                    // This prevents authentication bypass when prefix is empty
                    if prefix.is_empty() {
                        return Err(AuthError::MissingAuth);
                    }

                    if header_value.starts_with(&prefix) {
                        let key = &header_value[prefix.len()..];
                        if let Some(permissions) = auth.validate_key(key, &client_ip) {
                            Ok(AuthContext {
                                user_id: Some(AppApiKeyAuth::key_id(key)),
                                permissions,
                                metadata: crate::security::AuthMetadata::default(),
                            })
                        } else {
                            Err(AuthError::MissingAuth)
                        }
                    } else {
                        Err(AuthError::MissingAuth)
                    }
                };
            let middleware = auth_middleware(auth_clone, extract_auth);
            router = router.layer(axum::middleware::from_fn(middleware));
        } else if let AuthConfig::Jwt { secret, .. } = auth_config {
            let auth = Arc::new(BearerAuth::new(secret));
            let auth_clone = auth.clone();
            let extract_auth =
                move |req: &axum::http::Request<Body>| -> Result<AuthContext, AuthError> {
                    // Validate authorization header is present and properly formatted
                    // Empty or malformed headers must be rejected to prevent authentication bypass
                    let header_value = match req
                        .headers()
                        .get("authorization")
                        .and_then(|v: &HeaderValue| v.to_str().ok())
                    {
                        Some(value) => value,
                        None => return Err(AuthError::MissingAuth),
                    };

                    // Validate Bearer token format and non-empty token
                    // Note: "".strip_prefix("Bearer ") returns Some("") - empty token must be rejected
                    let token = match header_value.strip_prefix("Bearer ") {
                        Some(token) if !token.is_empty() => token,
                        _ => return Err(AuthError::InvalidToken),
                    };

                    if let Some(context) = auth.validate_token(token) {
                        Ok(context)
                    } else {
                        Err(AuthError::InvalidToken)
                    }
                };
            let middleware = auth_middleware(auth_clone, extract_auth);
            router = router.layer(axum::middleware::from_fn(middleware));
        }
        // OAuth2 is already checked before this block
        // None is handled by doing nothing
    }

    // Note: 日志初始化已移除，由使用方通过 sdforge::inklog 直接管理
    Ok(router)
}

/// Build HTTP router with hot reload support
///
/// This function builds a router with configuration hot reload support.
/// When the configuration file is modified, the router will automatically
/// reload and apply the new configuration.
///
/// # Arguments
/// * `config_path` - Path to the configuration file (YAML or JSON)
///
/// # Returns
/// A tuple containing:
/// * The configured Axum router
/// * A `ConfigWatcher` that manages configuration updates
///
/// # Example
/// ```no_run
/// use std::path::PathBuf;
///
/// #[tokio::main]
/// async fn main() -> Result<(), Box<dyn std::error::Error>> {
///     let config_path = PathBuf::from("config.toml");
///     let (router, config_watcher) =
///         sdforge::http::build_with_hot_reload(&config_path).await?;
///
///     // Use router and config_watcher as needed
///     let _ = (router, config_watcher);
///     Ok(())
/// }
/// ```
#[cfg(feature = "hot-reload")]
pub async fn build_with_hot_reload(
    config_path: &std::path::Path,
) -> Result<(Router, crate::config::hot_reload::ConfigWatcherImpl), Box<dyn std::error::Error>> {
    use crate::config::hot_reload::ConfigWatcherImpl;
    use std::path::PathBuf;

    let config_path = PathBuf::from(config_path);
    let (config_watcher, _event_receiver) = ConfigWatcherImpl::new(config_path.clone()).await?;

    // Build router with current configuration
    let config = config_watcher.get().await?;
    let router = build_with_config(&config)?;

    Ok((router, config_watcher))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{AppConfig, AuthConfig, CorsConfig, ServerConfig};
    use axum::routing::get;

    /// Test build() returns a valid Router
    #[test]
    fn test_build_returns_router() {
        let router = build();
        // Just verify it doesn't panic
        let _ = router;
    }

    /// Test build_with_redirect() returns Router with middleware
    #[test]
    fn test_build_with_redirect() {
        let router = build_with_redirect();
        // Should have layers applied
        let _ = router;
    }

    /// Test build_with_config with JWT authentication
    #[test]
    fn test_build_with_config_jwt() {
        let config = AppConfig {
            server: ServerConfig {
                host: "0.0.0.0".to_string(),
                port: 3000,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::Jwt {
                secret: "ThisIsAVeryLongSecretKeyWithUppercase123!@#ForTesting".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok(), "Should build successfully with JWT config");
    }

    /// Test build_with_config with ApiKey authentication
    #[test]
    fn test_build_with_config_api_key() {
        let config = AppConfig {
            server: ServerConfig {
                host: "0.0.0.0".to_string(),
                port: 3000,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::ApiKey {
                header_name: "X-API-Key".to_string(),
                prefix: "key-".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(
            result.is_ok(),
            "Should build successfully with ApiKey config"
        );
    }

    /// Test build_with_config with OAuth2 returns error
    #[test]
    fn test_build_with_config_oauth2_error() {
        let config = AppConfig {
            server: ServerConfig {
                host: "0.0.0.0".to_string(),
                port: 3000,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::None,
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok(), "Should succeed with None auth config");
    }

    /// Test build_with_config with CORS configuration
    #[test]
    fn test_build_with_config_cors() {
        let config = AppConfig {
            server: ServerConfig {
                host: "0.0.0.0".to_string(),
                port: 3000,
                request_timeout_secs: 30,
                cors: Some(CorsConfig {
                    allowed_origins: vec!["http://localhost:3000".to_string()],
                    allowed_methods: vec!["GET".to_string(), "POST".to_string()],
                    allowed_headers: vec!["Content-Type".to_string()],
                }),
            },
            authentication: AuthConfig::Jwt {
                secret: "ThisIsAVeryLongSecretKeyWithUppercase123!@#ForTesting".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok(), "Should build successfully with CORS config");
    }

    /// Test HttpRoute structure
    #[test]
    fn test_http_route_creation() {
        use axum::routing::get;

        async fn test_handler() -> &'static str {
            "test"
        }

        let route = HttpRoute::new(
            "/test".to_string(),
            get(test_handler),
            crate::core::ApiMetadata {
                name: "test".to_string(),
                version: "v1".to_string(),
                description: "Test API".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
            None,
        );

        assert_eq!(route.path(), "/test");
        assert_eq!(route.metadata().name(), "test");
        assert!(route.module_prefix().is_none());
    }

    /// Test resolve_route_path function
    #[test]
    fn test_resolve_route_path() {
        // No prefix
        assert_eq!(resolve_route_path("/api/users", None), "/api/users");
        assert_eq!(resolve_route_path("/api/users", Some("")), "/api/users");

        // With prefix
        assert_eq!(
            resolve_route_path("/api/users", Some("v1")),
            "/v1/api/users"
        );
        assert_eq!(
            resolve_route_path("/api/users", Some("/v1")),
            "/v1/api/users"
        );
    }

    /// Test RouteRegistration structure
    #[test]
    fn test_route_registration() {
        async fn test_handler() {}
        let registration = RouteRegistration::new(
            "test",
            "v1",
            || {
                HttpRoute::new(
                    "/test".to_string(),
                    get(test_handler),
                    crate::core::ApiMetadata {
                        name: "test".to_string(),
                        version: "v1".to_string(),
                        description: "".to_string(),
                        cache_ttl: None,
                        is_streaming: false,
                    },
                    None,
                )
            },
            || crate::core::ApiMetadata {
                name: "test".to_string(),
                version: "v1".to_string(),
                description: "".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
        );

        assert_eq!(registration.name, "test");
        assert_eq!(registration.version, "v1");
    }

    // ============================================================================
    // get_or_generate_request_id Tests
    // ============================================================================

    #[test]
    fn test_get_or_generate_request_id_with_header() {
        let req = axum::http::Request::builder()
            .header(X_REQUEST_ID, "my-custom-id-123")
            .body(Body::empty())
            .unwrap();

        let id = get_or_generate_request_id(&req);
        assert_eq!(id, "my-custom-id-123");
    }

    #[test]
    fn test_get_or_generate_request_id_without_header() {
        let req = axum::http::Request::builder().body(Body::empty()).unwrap();

        let id = get_or_generate_request_id(&req);
        // Should generate a valid UUID
        assert!(!id.is_empty());
        assert!(id.len() == 36); // UUID format: 8-4-4-4-12
    }

    #[test]
    fn test_get_or_generate_request_id_with_invalid_header_value() {
        // Header with non-UTF8 bytes should fall back to UUID generation
        let req = axum::http::Request::builder()
            .header(
                X_REQUEST_ID,
                axum::http::HeaderValue::from_bytes(b"\xff\xfe").unwrap(),
            )
            .body(Body::empty())
            .unwrap();

        let id = get_or_generate_request_id(&req);
        // Should generate a UUID since header value is not valid UTF-8
        assert!(!id.is_empty());
        assert!(id.len() == 36);
    }

    // ============================================================================
    // HttpRoute Extended Tests
    // ============================================================================

    #[test]
    fn test_http_route_with_module_prefix() {
        async fn test_handler() {}
        let route = HttpRoute::new(
            "/api/users".to_string(),
            get(test_handler),
            crate::core::ApiMetadata {
                name: "users".to_string(),
                version: "v1".to_string(),
                description: "Users API".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
            Some("v1".to_string()),
        );

        assert_eq!(route.path(), "/api/users");
        assert_eq!(route.module_prefix(), Some("v1"));
        assert_eq!(route.metadata().name(), "users");
    }

    #[test]
    fn test_http_route_handler_accessor() {
        async fn handler() -> &'static str {
            "handler"
        }
        let route = HttpRoute::new(
            "/test".to_string(),
            get(handler),
            crate::core::ApiMetadata {
                name: "test".to_string(),
                version: "v1".to_string(),
                description: "".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
            None,
        );

        // Verify handler accessor returns a reference
        let _handler = route.handler();
    }

    #[test]
    fn test_http_route_clone() {
        async fn handler() {}
        let route = HttpRoute::new(
            "/clone-test".to_string(),
            get(handler),
            crate::core::ApiMetadata {
                name: "clone".to_string(),
                version: "v1".to_string(),
                description: "Clone test".to_string(),
                cache_ttl: Some(60),
                is_streaming: false,
            },
            Some("api".to_string()),
        );

        let cloned = route.clone();
        assert_eq!(cloned.path(), route.path());
        assert_eq!(cloned.module_prefix(), route.module_prefix());
    }

    #[test]
    fn test_http_route_debug() {
        async fn handler() {}
        let route = HttpRoute::new(
            "/debug".to_string(),
            get(handler),
            crate::core::ApiMetadata {
                name: "debug".to_string(),
                version: "v1".to_string(),
                description: "Debug test".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
            None,
        );

        let debug_str = format!("{:?}", route);
        assert!(debug_str.contains("HttpRoute"));
    }

    // ============================================================================
    // RouteRegistration Extended Tests
    // ============================================================================

    #[test]
    fn test_route_registration_name_accessor() {
        async fn handler() {}
        let registration = RouteRegistration::new(
            "my_api",
            "v2",
            || {
                HttpRoute::new(
                    "/api".to_string(),
                    get(handler),
                    crate::core::ApiMetadata {
                        name: "my_api".to_string(),
                        version: "v2".to_string(),
                        description: "".to_string(),
                        cache_ttl: None,
                        is_streaming: false,
                    },
                    None,
                )
            },
            || crate::core::ApiMetadata {
                name: "my_api".to_string(),
                version: "v2".to_string(),
                description: "".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
        );

        assert_eq!(registration.name, "my_api");
    }

    #[test]
    fn test_route_registration_create() {
        async fn handler() {}
        let registration = RouteRegistration::new(
            "create_test",
            "v1",
            || {
                HttpRoute::new(
                    "/create".to_string(),
                    get(handler),
                    crate::core::ApiMetadata {
                        name: "create_test".to_string(),
                        version: "v1".to_string(),
                        description: "Create test".to_string(),
                        cache_ttl: None,
                        is_streaming: false,
                    },
                    None,
                )
            },
            || crate::core::ApiMetadata {
                name: "create_test".to_string(),
                version: "v1".to_string(),
                description: "Create test".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
        );

        let route = registration.create();
        assert_eq!(route.path(), "/create");
    }

    // ============================================================================
    // resolve_route_path Extended Tests
    // ============================================================================

    #[test]
    fn test_resolve_route_path_empty_prefix() {
        assert_eq!(resolve_route_path("/api/test", Some("")), "/api/test");
    }

    #[test]
    fn test_resolve_route_path_with_leading_slash() {
        assert_eq!(resolve_route_path("/api/test", Some("/v2")), "/v2/api/test");
    }

    #[test]
    fn test_resolve_route_path_root_path() {
        assert_eq!(resolve_route_path("/", Some("v1")), "/v1/");
    }

    // ============================================================================
    // Inventory Preservation Tests (feature-gated)
    // ============================================================================

    #[cfg(feature = "mcp")]
    #[test]
    fn test_preserve_mcp_inventory() {
        // This test verifies the MCP inventory preservation function doesn't panic
        // The function is called internally by build()
        preserve_mcp_inventory();
    }

    #[cfg(feature = "websocket")]
    #[test]
    fn test_preserve_websocket_inventory() {
        preserve_websocket_inventory();
    }

    #[cfg(feature = "grpc")]
    #[test]
    fn test_preserve_grpc_inventory() {
        preserve_grpc_inventory();
    }

    // ============================================================================
    // build() function extended tests
    // ============================================================================

    #[test]
    fn test_build_router_deterministic() {
        // Call build twice - should not panic
        let _router1 = build();
        let _router2 = build();
    }

    // ============================================================================
    // Security Headers Tests
    // ============================================================================

    #[test]
    fn test_apply_security_headers() {
        let router = Router::new();
        let router_with_headers = apply_security_headers(router);
        // Just verify it doesn't panic
        let _ = router_with_headers;
    }

    // ============================================================================
    // build() Extended Tests - Route Building with Various Configurations
    // ============================================================================

    #[test]
    fn test_build_with_direct_http_route_registration() {
        // Test that direct HttpRoute registrations are collected
        // This exercises line 171-173 in build()
        let router = build();
        // Should not panic even with no registered routes
        let _ = router;
    }

    #[test]
    fn test_build_sorts_routes_deterministically() {
        // Call build multiple times to verify deterministic behavior
        // Routes are sorted by path (line 176)
        let _router1 = build();
        let _router2 = build();
        // Both should succeed without panic
    }

    #[test]
    fn test_build_collects_registrations() {
        // This tests lines 162-168: collecting and creating from registrations
        let router = build();
        // Verify router is valid
        let _ = router;
    }

    // ============================================================================
    // build_with_config Extended Tests - Middleware Integration
    // ============================================================================

    #[test]
    fn test_build_with_config_request_id_middleware() {
        // Tests the request ID middleware (lines 226-240)
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 60,
                cors: None,
            },
            authentication: AuthConfig::None,
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_with_config_body_limit() {
        // Tests body limit layer (lines 243-245)
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::None,
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_with_config_compression_layer() {
        // Tests compression layer (line 248)
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::None,
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_with_config_timeout_layer() {
        // Tests timeout layer (lines 251-255)
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 5,
                cors: None,
            },
            authentication: AuthConfig::None,
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_with_config_zero_timeout() {
        // Test with zero timeout (edge case)
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 0,
                cors: None,
            },
            authentication: AuthConfig::None,
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_with_config_large_timeout() {
        // Test with large timeout value
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 3600,
                cors: None,
            },
            authentication: AuthConfig::None,
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_with_config_cors_various_origins() {
        // Test CORS with multiple origins
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: Some(CorsConfig {
                    allowed_origins: vec![
                        "http://localhost:3000".to_string(),
                        "http://example.com".to_string(),
                        "https://app.example.com".to_string(),
                    ],
                    allowed_methods: vec!["GET".to_string()],
                    allowed_headers: vec!["Content-Type".to_string()],
                }),
            },
            authentication: AuthConfig::None,
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_with_config_cors_all_methods() {
        // Test CORS with valid origins and common methods
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: Some(CorsConfig {
                    allowed_origins: vec![
                        "http://localhost:3000".to_string(),
                        "https://example.com".to_string(),
                    ],
                    allowed_methods: vec!["GET".to_string(), "POST".to_string()],
                    allowed_headers: vec!["Content-Type".to_string()],
                }),
            },
            authentication: AuthConfig::None,
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    // ============================================================================
    // Authentication Tests - ApiKey Edge Cases
    // ============================================================================

    #[test]
    fn test_build_with_config_api_key_empty_prefix() {
        // Test ApiKey with empty prefix (lines 306-308)
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::ApiKey {
                header_name: "X-API-Key".to_string(),
                prefix: "".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_with_config_api_key_long_prefix() {
        // Test ApiKey with long prefix
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::ApiKey {
                header_name: "X-Custom-API-Key".to_string(),
                prefix: "Bearer-api-key-".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_with_config_api_key_special_chars() {
        // Test ApiKey with special characters in prefix
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::ApiKey {
                header_name: "X-Api-Key".to_string(),
                prefix: "key_123-".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    // ============================================================================
    // Authentication Tests - JWT Edge Cases
    // ============================================================================

    #[test]
    fn test_build_with_config_jwt_short_secret() {
        // JWT requires minimum secret length and character classes
        // This tests that valid secrets work correctly
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::Jwt {
                secret: "ValidSecretKey123!@#WithUppercase".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_with_config_jwt_special_chars() {
        // Test JWT secret with special characters (must meet complexity requirements)
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::Jwt {
                secret: "SpecialChars!@#$%^&*()_+Secret123".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_with_config_jwt_empty_secret() {
        // Note: BearerAuth::new() panics with empty/invalid secrets.
        // This test uses a valid secret to verify build path works.
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::Jwt {
                secret: "ValidSecretForTesting123!@#WithUppercase".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok());
    }

    // ============================================================================
    // Feature-Gated Code Paths Tests
    // ============================================================================

    #[cfg(feature = "mcp")]
    #[test]
    fn test_build_preserves_mcp_inventory_with_routes() {
        // Test that MCP inventory is preserved when building router
        // This exercises lines 150-151
        let router = build();
        let _ = router;
    }

    #[cfg(feature = "websocket")]
    #[test]
    fn test_build_preserves_websocket_inventory_with_routes() {
        // Test that WebSocket inventory is preserved
        // This exercises lines 153-154
        let router = build();
        let _ = router;
    }

    #[cfg(feature = "grpc")]
    #[test]
    fn test_build_preserves_grpc_inventory_with_routes() {
        // Test that gRPC inventory is preserved
        // This exercises lines 156-157
        let router = build();
        let _ = router;
    }

    // ============================================================================
    // RouteRegistration Extended Tests - Metadata and Edge Cases
    // ============================================================================

    #[test]
    fn test_route_registration_metadata() {
        async fn handler() {}
        let registration = RouteRegistration::new(
            "metadata_test",
            "v1",
            || {
                HttpRoute::new(
                    "/metadata".to_string(),
                    get(handler),
                    crate::core::ApiMetadata {
                        name: "metadata_test".to_string(),
                        version: "v1".to_string(),
                        description: "Metadata test".to_string(),
                        cache_ttl: Some(300),
                        is_streaming: true,
                    },
                    None,
                )
            },
            || crate::core::ApiMetadata {
                name: "metadata_test".to_string(),
                version: "v1".to_string(),
                description: "Metadata test".to_string(),
                cache_ttl: Some(300),
                is_streaming: true,
            },
        );

        let metadata = registration.metadata();
        assert_eq!(metadata.name(), "metadata_test");
        assert!(metadata.is_streaming());
        assert_eq!(metadata.cache_ttl(), Some(300));
    }

    #[test]
    fn test_route_registration_debug() {
        async fn handler() {}
        let registration = RouteRegistration::new(
            "debug_test",
            "v1",
            || {
                HttpRoute::new(
                    "/debug".to_string(),
                    get(handler),
                    crate::core::ApiMetadata {
                        name: "debug_test".to_string(),
                        version: "v1".to_string(),
                        description: "".to_string(),
                        cache_ttl: None,
                        is_streaming: false,
                    },
                    None,
                )
            },
            || crate::core::ApiMetadata {
                name: "debug_test".to_string(),
                version: "v1".to_string(),
                description: "".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
        );

        let debug_str = format!("{:?}", registration);
        assert!(debug_str.contains("RouteRegistration"));
        assert!(debug_str.contains("debug_test"));
    }

    #[test]
    fn test_route_registration_clone() {
        async fn handler() {}
        let registration = RouteRegistration::new(
            "clone_test",
            "v1",
            || {
                HttpRoute::new(
                    "/clone".to_string(),
                    get(handler),
                    crate::core::ApiMetadata {
                        name: "clone_test".to_string(),
                        version: "v1".to_string(),
                        description: "".to_string(),
                        cache_ttl: None,
                        is_streaming: false,
                    },
                    None,
                )
            },
            || crate::core::ApiMetadata {
                name: "clone_test".to_string(),
                version: "v1".to_string(),
                description: "".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
        );

        let cloned = registration;
        assert_eq!(cloned.name, registration.name);
        assert_eq!(cloned.version, registration.version);
    }

    #[test]
    fn test_route_registration_copy() {
        async fn handler() {}
        let registration = RouteRegistration::new(
            "copy_test",
            "v1",
            || {
                HttpRoute::new(
                    "/copy".to_string(),
                    get(handler),
                    crate::core::ApiMetadata {
                        name: "copy_test".to_string(),
                        version: "v1".to_string(),
                        description: "".to_string(),
                        cache_ttl: None,
                        is_streaming: false,
                    },
                    None,
                )
            },
            || crate::core::ApiMetadata {
                name: "copy_test".to_string(),
                version: "v1".to_string(),
                description: "".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
        );

        let copied = registration; // RouteRegistration is Copy
        assert_eq!(copied.name, "copy_test");
    }

    // ============================================================================
    // HttpRoute with Various Path Configurations
    // ============================================================================

    #[test]
    fn test_http_route_with_root_path() {
        async fn handler() {}
        let route = HttpRoute::new(
            "/".to_string(),
            get(handler),
            crate::core::ApiMetadata {
                name: "root".to_string(),
                version: "v1".to_string(),
                description: "Root path".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
            None,
        );

        assert_eq!(route.path(), "/");
    }

    #[test]
    fn test_http_route_with_nested_path() {
        async fn handler() {}
        let route = HttpRoute::new(
            "/api/v1/users/:id/posts/:post_id".to_string(),
            get(handler),
            crate::core::ApiMetadata {
                name: "nested".to_string(),
                version: "v1".to_string(),
                description: "Nested path".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
            Some("api".to_string()),
        );

        assert_eq!(route.path(), "/api/v1/users/:id/posts/:post_id");
        assert_eq!(route.module_prefix(), Some("api"));
    }

    #[test]
    fn test_http_route_with_regex_path() {
        async fn handler() {}
        let route = HttpRoute::new(
            "/files/{*path}".to_string(),
            get(handler),
            crate::core::ApiMetadata {
                name: "wildcard".to_string(),
                version: "v1".to_string(),
                description: "Wildcard path".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
            None,
        );

        assert_eq!(route.path(), "/files/{*path}");
    }

    #[test]
    fn test_http_route_metadata_accessors() {
        async fn handler() {}
        let route = HttpRoute::new(
            "/test".to_string(),
            get(handler),
            crate::core::ApiMetadata {
                name: "full_test".to_string(),
                version: "v2".to_string(),
                description: "Full metadata test".to_string(),
                cache_ttl: Some(600),
                is_streaming: true,
            },
            Some("v2".to_string()),
        );

        let metadata = route.metadata();
        assert_eq!(metadata.name(), "full_test");
        assert_eq!(metadata.version(), "v2");
        assert_eq!(metadata.description(), "Full metadata test");
        assert_eq!(metadata.cache_ttl(), Some(600));
        assert!(metadata.is_streaming());
    }

    // ============================================================================
    // resolve_route_path Extended Edge Cases
    // ============================================================================

    #[test]
    fn test_resolve_route_path_deep_prefix() {
        assert_eq!(
            resolve_route_path("/api/users", Some("api/v1")),
            "/api/v1/api/users"
        );
    }

    #[test]
    fn test_resolve_route_path_multiple_leading_slashes() {
        assert_eq!(
            resolve_route_path("/api/users", Some("///v1")),
            "/v1/api/users"
        );
    }

    #[test]
    fn test_resolve_route_path_whitespace_prefix() {
        // Whitespace prefix is not empty, so it gets used
        let result = resolve_route_path("/api/users", Some(" "));
        assert_eq!(result, "/ /api/users");
    }

    // ============================================================================
    // build_with_config Integration Tests - All Middleware Combined
    // ============================================================================

    #[test]
    fn test_build_with_config_full_jwt_cors() {
        // Test with all middleware: JWT + CORS + security headers + timeout
        let config = AppConfig {
            server: ServerConfig {
                host: "0.0.0.0".to_string(),
                port: 443,
                request_timeout_secs: 15,
                cors: Some(CorsConfig {
                    allowed_origins: vec!["https://app.example.com".to_string()],
                    allowed_methods: vec!["GET".to_string(), "POST".to_string()],
                    allowed_headers: vec!["Content-Type".to_string(), "Authorization".to_string()],
                }),
            },
            authentication: AuthConfig::Jwt {
                secret: "AnotherVeryLongSecretKeyForTestingPurposes1234567890!".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok(), "Should build with full config");
    }

    #[test]
    fn test_build_with_config_full_api_key_cors() {
        // Test with all middleware: ApiKey + CORS + security headers + timeout
        let config = AppConfig {
            server: ServerConfig {
                host: "0.0.0.0".to_string(),
                port: 8443,
                request_timeout_secs: 20,
                cors: Some(CorsConfig {
                    allowed_origins: vec!["http://localhost:8080".to_string()],
                    allowed_methods: vec!["GET".to_string(), "POST".to_string(), "PUT".to_string()],
                    allowed_headers: vec!["Content-Type".to_string(), "X-API-Key".to_string()],
                }),
            },
            authentication: AuthConfig::ApiKey {
                header_name: "X-API-Key".to_string(),
                prefix: "sk-".to_string(),
            },
            timeout: None,
        };

        let result = build_with_config(&config);
        assert!(result.is_ok(), "Should build with full config");
    }

    // ============================================================================
    // build_with_redirect Extended Tests
    // ============================================================================

    #[test]
    fn test_build_with_redirect_multiple_calls() {
        // Test that build_with_redirect can be called multiple times
        let router1 = build_with_redirect();
        let router2 = build_with_redirect();

        // Both should be valid routers
        let _ = router1;
        let _ = router2;
    }

    // ============================================================================
    // X_REQUEST_ID Constant Tests
    // ============================================================================

    #[test]
    fn test_x_request_id_constant() {
        assert_eq!(X_REQUEST_ID, "x-request-id");
    }

    // ============================================================================
    // Inventory Collection Tests
    // ============================================================================

    #[test]
    fn test_inventory_http_route_collection() {
        // Verify that inventory::iter::<HttpRoute> works
        // This exercises line 171 in build()
        let count = inventory::iter::<HttpRoute>().count();
        // Count may be 0 or more depending on registered routes
        let _ = count;
    }

    #[test]
    fn test_inventory_route_registration_collection() {
        // Verify that inventory::iter::<RouteRegistration> works
        // This exercises line 162 in build()
        let count = inventory::iter::<RouteRegistration>().count();
        let _ = count;
    }

    // ============================================================================
    // Inventory-Registered Test Route (covers build() route collection, lines 162-183)
    // ============================================================================

    fn coverage_test_route_create() -> HttpRoute {
        HttpRoute::new(
            "/cov-test-route".to_string(),
            get(|| async { "coverage-test-ok" }),
            crate::core::ApiMetadata {
                name: "cov_test_route".to_string(),
                version: "v1".to_string(),
                description: "Coverage test route".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
            None,
        )
    }

    fn coverage_test_route_metadata() -> crate::core::ApiMetadata {
        crate::core::ApiMetadata {
            name: "cov_test_route".to_string(),
            version: "v1".to_string(),
            description: "Coverage test route".to_string(),
            cache_ttl: None,
            is_streaming: false,
        }
    }

    inventory::submit!(RouteRegistration::new(
        "cov_test_route",
        "v1",
        coverage_test_route_create,
        coverage_test_route_metadata,
    ));

    // ============================================================================
    // Request ID Middleware Execution Tests (covers lines 226-244)
    // These tests send real requests through the router to exercise the
    // middleware closure body, which is never executed by build-only tests.
    // ============================================================================

    #[tokio::test]
    async fn test_request_id_middleware_generates_uuid_when_absent() {
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::None,
            timeout: None,
        };
        let router = build_with_config(&config).unwrap();
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::OK);
        let request_id = response
            .headers()
            .get(X_REQUEST_ID)
            .expect("response should have x-request-id header");
        let id_str = request_id.to_str().unwrap();
        assert_eq!(id_str.len(), 36, "generated request ID should be a UUID");
    }

    #[tokio::test]
    async fn test_request_id_middleware_preserves_custom_id() {
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::None,
            timeout: None,
        };
        let router = build_with_config(&config).unwrap();
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .header(X_REQUEST_ID, "my-custom-id-789")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::OK);
        let request_id = response.headers().get(X_REQUEST_ID).unwrap();
        assert_eq!(request_id.to_str().unwrap(), "my-custom-id-789");
    }

    #[tokio::test]
    async fn test_request_id_middleware_non_utf8_header_generates_uuid() {
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::None,
            timeout: None,
        };
        let router = build_with_config(&config).unwrap();
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .header(
                    X_REQUEST_ID,
                    axum::http::HeaderValue::from_bytes(b"\xff\xfe").unwrap(),
                )
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::OK);
        let request_id = response.headers().get(X_REQUEST_ID).unwrap();
        let id_str = request_id.to_str().unwrap();
        assert_eq!(id_str.len(), 36, "should generate UUID for non-UTF8 header");
    }

    // ============================================================================
    // Inventory Route Accessibility Test (covers build() route collection loop)
    // ============================================================================

    #[tokio::test]
    async fn test_build_includes_inventory_registered_route() {
        let router = build();
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::OK);
        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        assert_eq!(&body[..], b"coverage-test-ok");
    }

    // ============================================================================
    // JWT Auth Middleware Execution Tests (security feature, covers lines 334-359)
    // These tests exercise the extract_auth closure body for JWT auth.
    // ============================================================================

    #[cfg(feature = "security")]
    fn create_test_jwt(secret: &[u8], payload: &serde_json::Value) -> String {
        use base64::Engine;
        use hmac::{Hmac, Mac};
        use sha2::Sha256;

        let header = serde_json::json!({"alg": "HS256", "typ": "JWT"});
        let header_b64 = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .encode(serde_json::to_string(&header).unwrap());
        let payload_b64 = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .encode(serde_json::to_string(payload).unwrap());

        let signing_input = format!("{}.{}", header_b64, payload_b64);
        let mut mac =
            Hmac::<Sha256>::new_from_slice(secret).expect("HMAC can take key of any size");
        mac.update(signing_input.as_bytes());
        let signature = mac.finalize().into_bytes();
        let signature_b64 =
            base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(signature);

        format!("{}.{}", signing_input, signature_b64)
    }

    #[cfg(feature = "security")]
    fn build_jwt_test_router(secret: &str) -> Router {
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::Jwt {
                secret: secret.to_string(),
            },
            timeout: None,
        };
        build_with_config(&config).unwrap()
    }

    #[cfg(feature = "security")]
    #[tokio::test]
    async fn test_jwt_auth_missing_header_returns_401() {
        let router = build_jwt_test_router("MySecureSecret123!@#ABCDEFGHIJKLM");
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::UNAUTHORIZED);
    }

    #[cfg(feature = "security")]
    #[tokio::test]
    async fn test_jwt_auth_non_bearer_token_returns_401() {
        let router = build_jwt_test_router("MySecureSecret123!@#ABCDEFGHIJKLM");
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .header("authorization", "Basic dXNlcjpwYXNz")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::UNAUTHORIZED);
    }

    #[cfg(feature = "security")]
    #[tokio::test]
    async fn test_jwt_auth_empty_bearer_token_returns_401() {
        let router = build_jwt_test_router("MySecureSecret123!@#ABCDEFGHIJKLM");
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .header("authorization", "Bearer ")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::UNAUTHORIZED);
    }

    #[cfg(feature = "security")]
    #[tokio::test]
    async fn test_jwt_auth_invalid_token_returns_401() {
        let router = build_jwt_test_router("MySecureSecret123!@#ABCDEFGHIJKLM");
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .header("authorization", "Bearer invalid.token.here")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::UNAUTHORIZED);
    }

    #[cfg(feature = "security")]
    #[tokio::test]
    async fn test_jwt_auth_valid_token_returns_200() {
        let secret = "MySecureSecret123!@#ABCDEFGHIJKLM";
        let router = build_jwt_test_router(secret);

        let payload = serde_json::json!({
            "sub": "test-user",
            "permissions": ["read"],
            "iat": chrono::Utc::now().timestamp(),
            "exp": chrono::Utc::now().timestamp() + 3600
        });
        let token = create_test_jwt(secret.as_bytes(), &payload);

        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .header("authorization", format!("Bearer {}", token))
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::OK);
    }

    // ============================================================================
    // ApiKey Auth Middleware Execution Tests (security feature, covers lines 288-328)
    // These tests exercise the extract_auth closure body for ApiKey auth.
    //
    // NOTE: The ApiKey success path (lines 316-321) is UNREACHABLE through
    // build_with_config() because AppApiKeyAuth::new() creates an empty
    // authenticator with no registered keys. All valid-format keys will fail
    // validation. This is a design limitation of build_with_config().
    // ============================================================================

    #[cfg(feature = "security")]
    fn build_apikey_test_router(header_name: &str, prefix: &str) -> Router {
        let config = AppConfig {
            server: ServerConfig {
                host: "127.0.0.1".to_string(),
                port: 8080,
                request_timeout_secs: 30,
                cors: None,
            },
            authentication: AuthConfig::ApiKey {
                header_name: header_name.to_string(),
                prefix: prefix.to_string(),
            },
            timeout: None,
        };
        build_with_config(&config).unwrap()
    }

    #[cfg(feature = "security")]
    #[tokio::test]
    async fn test_apikey_auth_missing_header_returns_401() {
        let router = build_apikey_test_router("X-API-Key", "key-");
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::UNAUTHORIZED);
    }

    #[cfg(feature = "security")]
    #[tokio::test]
    async fn test_apikey_auth_wrong_prefix_returns_401() {
        let router = build_apikey_test_router("X-API-Key", "key-");
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .header("X-API-Key", "Bearer-something")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::UNAUTHORIZED);
    }

    #[cfg(feature = "security")]
    #[tokio::test]
    async fn test_apikey_auth_empty_prefix_returns_401() {
        // Config with empty prefix — security check rejects empty prefix (lines 310-312)
        let router = build_apikey_test_router("X-API-Key", "");
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .header("X-API-Key", "some-key-value")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::UNAUTHORIZED);
    }

    #[cfg(feature = "security")]
    #[tokio::test]
    async fn test_apikey_auth_unregistered_key_returns_401() {
        // Valid format (correct prefix) but key is not registered in the
        // empty AppApiKeyAuth — validate_key returns None (lines 322-324)
        let router = build_apikey_test_router("X-API-Key", "key-");
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .header("X-API-Key", "key-unregistered-key-123")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::UNAUTHORIZED);
    }

    #[cfg(feature = "security")]
    #[tokio::test]
    async fn test_apikey_auth_with_x_forwarded_for_header() {
        // Test client IP extraction path (lines 300-306) with x-forwarded-for
        let router = build_apikey_test_router("X-API-Key", "key-");
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .header("X-API-Key", "key-test")
                .header("x-forwarded-for", "203.0.113.50")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        // Should still be 401 because key is not registered
        assert_eq!(response.status(), axum::http::StatusCode::UNAUTHORIZED);
    }

    #[cfg(feature = "security")]
    #[tokio::test]
    async fn test_apikey_auth_with_x_real_ip_header() {
        // Test client IP extraction fallback to x-real-ip (lines 302-304)
        let router = build_apikey_test_router("X-API-Key", "key-");
        let response = tower::ServiceExt::oneshot(
            router,
            axum::http::Request::builder()
                .uri("/cov-test-route")
                .header("X-API-Key", "key-test")
                .header("x-real-ip", "203.0.113.99")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

        assert_eq!(response.status(), axum::http::StatusCode::UNAUTHORIZED);
    }

    // ============================================================================
    // Hot Reload Test (hot-reload feature, covers lines 401-415)
    // ============================================================================

    #[cfg(feature = "hot-reload")]
    #[tokio::test]
    async fn test_build_with_hot_reload_valid_config() {
        use std::io::Write;
        use tempfile::NamedTempFile;

        let toml_content = r#"
[server]
host = "127.0.0.1"
port = 8080
request_timeout_secs = 30

[authentication]
type = "none"
"#;

        let mut temp_file = NamedTempFile::new().unwrap();
        temp_file.write_all(toml_content.as_bytes()).unwrap();
        let temp_path = temp_file.path().to_path_buf();

        let result = build_with_hot_reload(&temp_path).await;
        assert!(
            result.is_ok(),
            "build_with_hot_reload should succeed: {:?}",
            result.err()
        );

        if let Ok((router, watcher)) = result {
            assert_eq!(watcher.path(), &temp_path);
            let _ = router;
        }

        // temp_file is dropped here, cleaning up the file
    }
}
