// Copyright (c) 2026 Kirky.X
//! MCP server implementation

use crate::core::ApiMetadata;
#[cfg(feature = "mcp")]
use serde_json::Value;
use std::sync::Arc;

/// Wrapper for Arc<dyn Tool> to implement Tool trait
#[cfg(feature = "mcp")]
struct ArcToolWrapper {
    inner: Arc<dyn mcp_sdk::tools::Tool>,
}

#[cfg(feature = "mcp")]
impl mcp_sdk::tools::Tool for ArcToolWrapper {
    fn name(&self) -> String {
        self.inner.name()
    }

    fn description(&self) -> String {
        self.inner.description()
    }

    fn input_schema(&self) -> serde_json::Value {
        self.inner.input_schema()
    }

    fn call(
        &self,
        input: Option<Value>,
    ) -> Result<mcp_sdk::types::CallToolResponse, anyhow::Error> {
        self.inner.call(input)
    }
}

/// MCP tool instance registration with Arc for shared ownership
///
/// This structure stores the actual Tool implementation generated by macros,
/// allowing the runtime to directly use the macro-generated tool instances.
#[cfg(feature = "mcp")]
pub struct McpToolInstance {
    /// The actual Tool implementation (Arc for shared ownership)
    pub tool: Arc<dyn mcp_sdk::tools::Tool>,
    /// API metadata
    pub metadata: ApiMetadata,
}

#[cfg(feature = "mcp")]
inventory::collect!(McpToolInstance);

/// Build MCP server from registered tools
#[cfg(feature = "mcp")]
pub async fn build() -> mcp_sdk::server::Server<mcp_sdk::transport::ServerStdioTransport> {
    use mcp_sdk::server::Server;
    use mcp_sdk::tools::Tools;
    use mcp_sdk::transport::ServerStdioTransport;

    let mut tools = Tools::default();
    let mut server_name = "axiom-mcp".to_string();
    let mut server_version = "0.1.0".to_string();

    // Collect all registered tool instances
    for instance in inventory::iter::<McpToolInstance> {
        // Wrap Arc<dyn Tool> in ArcToolWrapper to satisfy Tool trait bound
        let wrapper = ArcToolWrapper {
            inner: instance.tool.clone(),
        };
        tools.add_tool(wrapper);

        // Use the first tool's metadata for server info
        if server_name == "axiom-mcp" {
            server_name = instance.metadata.name().to_string();
            server_version = instance.metadata.version().to_string();
        }
    }

    Server::builder(ServerStdioTransport)
        .name(server_name)
        .version(server_version)
        .tools(tools)
        .build()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::ApiMetadata;
    use std::sync::Arc;

    /// Test ApiMetadata structure
    #[test]
    fn test_api_metadata_creation() {
        let metadata = ApiMetadata {
            name: "test_tool".to_string(),
            version: "v1".to_string(),
            description: "A test tool".to_string(),
            cache_ttl: None,
            is_streaming: false,
        };
        assert_eq!(metadata.name, "test_tool");
        assert_eq!(metadata.version, "v1");
        assert_eq!(metadata.description, "A test tool");
    }

    /// Test ApiMetadata name and version accessors
    #[test]
    fn test_api_metadata_accessors() {
        let metadata = ApiMetadata {
            name: "my_api".to_string(),
            version: "v2".to_string(),
            description: "".to_string(),
            cache_ttl: Some(300),
            is_streaming: true,
        };
        assert_eq!(metadata.name(), "my_api");
        assert_eq!(metadata.version(), "v2");
    }

    /// Test McpToolInstance structure (compile check only, as Tool trait requires mcp-sdk)
    #[cfg(feature = "mcp")]
    #[test]
    fn test_mcp_tool_instance_structure() {
        // This test verifies the structure compiles correctly
        // Full functionality tests require mcp-sdk mock implementations
        struct MockTool;
        impl mcp_sdk::tools::Tool for MockTool {
            fn name(&self) -> String {
                "mock_tool".to_string()
            }
            fn description(&self) -> String {
                "Mock tool for testing".to_string()
            }
            fn input_schema(&self) -> serde_json::Value {
                serde_json::json!({"type": "object"})
            }
            fn call(
                &self,
                _input: Option<serde_json::Value>,
            ) -> Result<mcp_sdk::types::CallToolResponse, anyhow::Error> {
                Ok(mcp_sdk::types::CallToolResponse {
                    content: vec![],
                    is_error: None,
                    meta: None,
                })
            }
        }

        let instance = McpToolInstance {
            tool: Arc::new(MockTool) as Arc<dyn mcp_sdk::tools::Tool>,
            metadata: ApiMetadata {
                name: "test".to_string(),
                version: "v1".to_string(),
                description: "test".to_string(),
                cache_ttl: None,
                is_streaming: false,
            },
        };

        assert_eq!(instance.metadata.name, "test");
    }

    /// Test ApiMetadata creation for MCP tools
    #[test]
    fn test_api_metadata_for_mcp() {
        let metadata = ApiMetadata {
            name: "mcp_tool".to_string(),
            version: "v1".to_string(),
            description: "MCP tool".to_string(),
            cache_ttl: None,
            is_streaming: false,
        };
        assert_eq!(metadata.name(), "mcp_tool");
        assert_eq!(metadata.version(), "v1");
        assert!(metadata.cache_ttl().is_none());
        assert!(!metadata.is_streaming());
    }
}
