//! MCP server implementation

#[cfg(feature = "mcp")]
use serde_json::Value;
use crate::core::ApiMetadata;
use std::sync::Arc;

/// Wrapper for Arc<dyn Tool> to implement Tool trait
#[cfg(feature = "mcp")]
struct ArcToolWrapper {
    inner: Arc<dyn mcp_sdk::tools::Tool>,
}

#[cfg(feature = "mcp")]
impl mcp_sdk::tools::Tool for ArcToolWrapper {
    fn name(&self) -> String {
        self.inner.name()
    }

    fn description(&self) -> String {
        self.inner.description()
    }

    fn input_schema(&self) -> serde_json::Value {
        self.inner.input_schema()
    }

    fn call(&self, input: Option<Value>) -> Result<mcp_sdk::types::CallToolResponse, anyhow::Error> {
        self.inner.call(input)
    }
}

/// MCP tool instance registration with Arc for shared ownership
/// 
/// This structure stores the actual Tool implementation generated by macros,
/// allowing the runtime to directly use the macro-generated tool instances.
#[cfg(feature = "mcp")]
pub struct McpToolInstance {
    /// The actual Tool implementation (Arc for shared ownership)
    pub tool: Arc<dyn mcp_sdk::tools::Tool>,
    /// API metadata
    pub metadata: ApiMetadata,
}

#[cfg(feature = "mcp")]
inventory::collect!(McpToolInstance);

/// Build MCP server from registered tools
#[cfg(feature = "mcp")]
pub async fn build() -> mcp_sdk::server::Server<mcp_sdk::transport::ServerStdioTransport> {
    use mcp_sdk::server::Server;
    use mcp_sdk::tools::Tools;
    use mcp_sdk::transport::ServerStdioTransport;

    let mut tools = Tools::default();
    let mut server_name = "axiom-mcp".to_string();
    let mut server_version = "0.1.0".to_string();

    // Collect all registered tool instances
    for instance in inventory::iter::<McpToolInstance> {
        // Wrap Arc<dyn Tool> in ArcToolWrapper to satisfy Tool trait bound
        let wrapper = ArcToolWrapper {
            inner: instance.tool.clone(),
        };
        tools.add_tool(wrapper);
        
        // Use the first tool's metadata for server info
        if server_name == "axiom-mcp" {
            server_name = instance.metadata.name.to_string();
            server_version = instance.metadata.version.to_string();
        }
    }

    Server::builder(ServerStdioTransport)
        .name(server_name)
        .version(server_version)
        .tools(tools)
        .build()
}
