// Copyright (c) 2026 Kirky.X
//! Unified registration system for eliminating code duplication across protocols
//!
//! This module provides a trait-based abstraction for protocol registration,
//! allowing HTTP, MCP, WebSocket, and gRPC to share a common registration pattern.
//!
//! # Design Goals
//!
//! - Eliminate ~200+ lines of duplicate registration code
//! - Provide type-safe abstraction through traits
//! - Support future protocol extensions
//! - Maintain backward compatibility
//!
//! # Usage
//!
//! ```rust,ignore
//! use sdforge::core::registration::{Registration, define_registration};
//!
//! // Use the macro to define a registration type
//! define_registration!(RouteRegistration, HttpRoute, ApiMetadata);
//! ```

/// Core trait for all protocol registrations
///
/// This trait abstracts the common pattern used by HTTP routes, MCP tools,
/// WebSocket handlers, and gRPC services. Each protocol implements this trait
/// with their specific instance and metadata types.
///
/// # Type Parameters
///
/// - `Instance`: The concrete type created by this registration (e.g., `HttpRoute`, `Arc<dyn Tool>`)
/// - `Metadata`: Metadata associated with the registration (typically `ApiMetadata`)
///
/// # Examples
///
/// ```rust,ignore
/// impl Registration for RouteRegistration {
///     type Instance = HttpRoute;
///     type Metadata = ApiMetadata;
///
///     fn name(&self) -> &str { self.name }
///     fn version(&self) -> &str { self.version }
///     fn create(&self) -> Self::Instance { (self.create_fn)() }
///     fn metadata(&self) -> Self::Metadata { (self.metadata_fn)() }
/// }
/// ```
pub trait Registration: 'static + Send + Sync {
    /// The concrete instance type created by this registration
    type Instance;
    
    /// The metadata type associated with this registration
    type Metadata;
    
    /// Get the API name
    fn name(&self) -> &str;
    
    /// Get the API version
    fn version(&self) -> &str;
    
    /// Create a new instance
    fn create(&self) -> Self::Instance;
    
    /// Get the metadata
    fn metadata(&self) -> Self::Metadata;
}

/// Macro for defining registration types
///
/// This macro generates the boilerplate code for implementing the `Registration` trait.
/// It creates a struct with the necessary fields and implements the trait automatically.
///
/// # Syntax
///
/// ```rust,ignore
/// define_registration!(RegistrationTypeName, InstanceType, MetadataType);
/// ```
///
/// # Arguments
///
/// - `$name`: Name of the registration struct to create
/// - `$instance`: The instance type (e.g., `HttpRoute`, `Arc<dyn Tool>`)
/// - `$metadata`: The metadata type (e.g., `ApiMetadata`)
///
/// # Generated Code
///
/// The macro generates:
/// - A struct with `name`, `version`, `create_fn`, and `metadata_fn` fields
/// - Implementation of the `Registration` trait
/// - `inventory::collect!` call for automatic registration
///
/// # Examples
///
/// ```rust,ignore
/// // Define HTTP route registration
/// define_registration!(RouteRegistration, HttpRoute, ApiMetadata);
///
/// // Define MCP tool registration
/// define_registration!(McpToolRegistration, Arc<dyn Tool>, ApiMetadata);
///
/// // Define WebSocket route registration
/// define_registration!(WebSocketRouteRegistration, WebSocketHandler, ApiMetadata);
///
/// // Define gRPC service registration
/// define_registration!(GrpcServiceRegistration, GrpcService, ApiMetadata);
/// ```
#[macro_export]
macro_rules! define_registration {
    ($name:ident, $instance:ty, $metadata:ty) => {
        #[derive(Debug, Clone, Copy)]
        /// Registration entry for protocol-specific APIs
        /// 
        /// This struct is generated by the `define_registration!` macro and contains
        /// metadata and factory functions for a specific API registration.
        pub struct $name {
            /// API name
            pub name: &'static str,
            /// API version
            pub version: &'static str,
            /// Function that creates the instance at runtime
            pub create_fn: fn() -> $instance,
            /// Function that creates the metadata at runtime
            pub metadata_fn: fn() -> $metadata,
        }
        
        impl $name {
            /// Create a new registration instance
            ///
            /// # Arguments
            ///
            /// * `name` - API name
            /// * `version` - API version
            /// * `create_fn` - Function to create the instance
            /// * `metadata_fn` - Function to create the metadata
            #[allow(dead_code)]
            pub const fn new(
                name: &'static str,
                version: &'static str,
                create_fn: fn() -> $instance,
                metadata_fn: fn() -> $metadata,
            ) -> Self {
                Self {
                    name,
                    version,
                    create_fn,
                    metadata_fn,
                }
            }
        }
        
        impl $crate::core::registration::Registration for $name {
            type Instance = $instance;
            type Metadata = $metadata;
            
            fn name(&self) -> &str { self.name }
            fn version(&self) -> &str { self.version }
            fn create(&self) -> Self::Instance { (self.create_fn)() }
            fn metadata(&self) -> Self::Metadata { (self.metadata_fn)() }
        }
        
        // Register with inventory for automatic collection
        inventory::collect!($name);
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    
    // Mock types for testing
    pub struct MockInstance {
        pub _data: String,
    }
    
    pub struct MockMetadata {
        pub _name: String,
    }
    
    // Test the macro-generated code
    define_registration!(TestRegistration, MockInstance, MockMetadata);
    
    /// Test that Registration trait methods work correctly
    #[test]
    fn test_registration_trait_methods() {
        let reg = TestRegistration::new(
            "test_api",
            "v1",
            || MockInstance { _data: "test".to_string() },
            || MockMetadata { _name: "test".to_string() },
        );
        
        assert_eq!(reg.name(), "test_api");
        assert_eq!(reg.version(), "v1");
        
        let instance = reg.create();
        assert!(instance._data == "test");
        
        let metadata = reg.metadata();
        assert!(metadata._name == "test");
    }
    
    /// Test that Registration trait bounds are satisfied
    #[test]
    fn test_registration_trait_bounds() {
        fn requires_send_sync<T: Send + Sync>() {}
        fn requires_static<T: 'static>() {}
        
        // Should compile without errors
        requires_send_sync::<TestRegistration>();
        requires_static::<TestRegistration>();
    }
    
    /// Test multiple registration instances
    #[test]
    fn test_multiple_registrations() {
        define_registration!(TestReg1, MockInstance, MockMetadata);
        define_registration!(TestReg2, MockInstance, MockMetadata);
        
        let reg1 = TestReg1::new("api1", "v1", 
            || MockInstance { _data: "1".to_string() },
            || MockMetadata { _name: "1".to_string() });
        
        let reg2 = TestReg2::new("api2", "v2",
            || MockInstance { _data: "2".to_string() },
            || MockMetadata { _name: "2".to_string() });
        
        assert_eq!(reg1.name(), "api1");
        assert_eq!(reg2.name(), "api2");
        assert_ne!(reg1.name(), reg2.name());
    }
}
